---
title: C6318 |Microsoft 文件
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-code-analysis
ms.topic: conceptual
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: douge
ms.workload:
- multiple
ms.openlocfilehash: deb8de9e766282b305ddce61157a32a3c2585b35
ms.sourcegitcommit: 6a9d5bd75e50947659fd6c837111a6a547884e2a
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 04/16/2018
---
# <a name="c6318"></a>C6318
警告 C6318: for __try /\__except： 使用常數 EXCEPTION_CONTINUE_SEARCH 或評估為零的例外狀況篩選條件運算式中的另一個常數。 例外狀況處理常式區塊中的程式碼未執行  
  
 這個警告指出，此結構化例外狀況處理常式的受保護區塊中發生的例外狀況，例外狀況並不會處理因為常數`EXCECPTION_CONTINUE_SEARCH`例外狀況篩選條件運算式中使用。  
  
 因為處理常式區塊將會執行，此程式碼就相當於例外狀況處理常式區塊沒有受保護區塊。  
  
## <a name="example"></a>範例  
 下列程式碼會產生這個警告：  
  
```  
#include <excpt.h>  
#include <stdio.h>  
  
void f (char *pch)  
{  
  __try   
  {  
    // assignment might fail  
    *pch = 0;  
  }   
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318  
  {  
    puts("Exception Occurred");  
  }  
}  
```  
  
 若要修正這個警告，請使用下列程式碼：  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *pch)  
{  
  __try   
  {  
    // assignment might fail  
    *pch = 0;  
  }   
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?  
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )  
  {  
    puts("Access violation");  
  }  
}   
```  
  
## <a name="see-also"></a>另請參閱  
 [try-except 陳述式](/cpp/cpp/try-except-statement)